/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author M.Bayhaqi Lubis
 */
public class muhammadbayhaqi extends javax.swing.JFrame {
    String angka;
    double jumlah,button1,button2;
    int pilih;
    
    /**
     * Creates new form kalkulatorlatihan
     */
    public muhammadbayhaqi() {
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAngka0 = new javax.swing.JButton();
        btnKoma = new javax.swing.JButton();
        btnSamadengan = new javax.swing.JButton();
        bntAngka1 = new javax.swing.JButton();
        btnAngka2 = new javax.swing.JButton();
        btnAngka3 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnAngka4 = new javax.swing.JButton();
        btnAngka5 = new javax.swing.JButton();
        btnAngka6 = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnAngka7 = new javax.swing.JButton();
        btnAngka8 = new javax.swing.JButton();
        btnAngka9 = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAngka0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka0.setText("0");
        getContentPane().add(btnAngka0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 210, 80));

        btnKoma.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnKoma.setText(",");
        btnKoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKomaActionPerformed(evt);
            }
        });
        getContentPane().add(btnKoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 100, 80));

        btnSamadengan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSamadengan.setText("=");
        btnSamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSamadenganActionPerformed(evt);
            }
        });
        getContentPane().add(btnSamadengan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 100, 80));

        bntAngka1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bntAngka1.setText("1");
        bntAngka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAngka1ActionPerformed(evt);
            }
        });
        getContentPane().add(bntAngka1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 60));

        btnAngka2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka2.setText("2");
        btnAngka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 60));

        btnAngka3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka3.setText("3");
        btnAngka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 100, 60));

        btnTambah.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 100, 60));

        btnAngka4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka4.setText("4");
        btnAngka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 70));

        btnAngka5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka5.setText("5");
        btnAngka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 70));

        btnAngka6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka6.setText("6");
        btnAngka6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, 70));

        btnKurang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });
        getContentPane().add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 100, 60));

        btnAngka7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka7.setText("7");
        btnAngka7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 70));

        btnAngka8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka8.setText("8");
        btnAngka8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, 70));

        btnAngka9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAngka9.setText("9");
        btnAngka9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAngka9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAngka9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 100, 70));

        btnBagi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBagi.setText("/");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });
        getContentPane().add(btnBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 100, 70));

        btnKali.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnKali.setText("*");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 100, 70));

        btnHapus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnHapus.setText("c");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, 70));

        Display.setEditable(false);
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 420, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      button1=Double.parseDouble(angka);
      Display.setText("+");
      angka="";
      pilih=1;

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKomaActionPerformed
      angka += ",";
      Display.setText(angka);
    }//GEN-LAST:event_btnKomaActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        button1=Double.parseDouble(angka);
        Display.setText("/");
        angka="";
        pilih=4;

    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnAngka7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka7ActionPerformed
        angka += "7";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka7ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        Display.setText ("");
        jumlah=0;
        angka= "";
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnAngka8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka8ActionPerformed
        angka += "8";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka8ActionPerformed

    private void btnAngka9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka9ActionPerformed
        angka += "9";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka9ActionPerformed

    private void btnAngka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka4ActionPerformed
        angka += "4";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka4ActionPerformed

    private void btnAngka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka5ActionPerformed
        angka += "5";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka5ActionPerformed

    private void btnAngka6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka6ActionPerformed
        angka += "6";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka6ActionPerformed

    private void bntAngka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAngka1ActionPerformed
        angka += "1";
        Display.setText(angka);
    }//GEN-LAST:event_bntAngka1ActionPerformed

    private void btnAngka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka2ActionPerformed
        angka += "2";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka2ActionPerformed

    private void btnAngka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAngka3ActionPerformed
        angka += "3";
        Display.setText(angka);
    }//GEN-LAST:event_btnAngka3ActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        button1=Double.parseDouble(angka);
        Display.setText("-");
        angka="";
        pilih=2;
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        button1=Double.parseDouble(angka);
        Display.setText("*");
        angka="";
        pilih=3;
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnSamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSamadenganActionPerformed
            switch(pilih){
        case 1:
            button2 = Double.parseDouble(angka);
            jumlah = button1 + button2;
            angka = Double.toString(jumlah);
            Display.setText(angka);
            break;
        case 2:
            button2 = Double.parseDouble(angka);
            jumlah = button1 - button2;
            angka = Double.toString(jumlah);
            Display.setText(angka);
            break;
        case 3:
            button2 = Double.parseDouble(angka);
            jumlah = button2 * button1;
            angka = Double.toString(jumlah);
            Display.setText(angka);
            break;
        case 4:
            button2 = Double.parseDouble(angka);
            jumlah = button1 / button2;
            angka = Double.toString(jumlah);
            Display.setText(angka);
            break;
            default:
            break;
} 

    }//GEN-LAST:event_btnSamadenganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(muhammadbayhaqi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new muhammadbayhaqi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Display;
    private javax.swing.JButton bntAngka1;
    private javax.swing.JButton btnAngka0;
    private javax.swing.JButton btnAngka2;
    private javax.swing.JButton btnAngka3;
    private javax.swing.JButton btnAngka4;
    private javax.swing.JButton btnAngka5;
    private javax.swing.JButton btnAngka6;
    private javax.swing.JButton btnAngka7;
    private javax.swing.JButton btnAngka8;
    private javax.swing.JButton btnAngka9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKoma;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnSamadengan;
    private javax.swing.JButton btnTambah;
    // End of variables declaration//GEN-END:variables
}
